#define WKT_NUM                         1
#define WKT_POINT_TAGGED_TEXT           2
#define WKT_EMPTY_SET                   3
#define WKT_LPAREN                      4
#define WKT_RPAREN                      5
#define WKT_POINT_Z_TAGGED_TEXT         6
#define WKT_POINT_M_TAGGED_TEXT         7
#define WKT_POINT_ZM_TAGGED_TEXT        8
#define WKT_END_OF_INPUT                99
#define WKT_PARSE_ERROR                 100