/* Generated by re2c 1.1.1 on Sat Feb 16 00:38:55 2019 */
#pragma once

#include <iostream>

namespace simo
{
namespace shapes
{

class wkt_lexer
{
  public:
    enum token_type
    {
        point_tagged_text,
        point_z_tagged_text,
        point_m_tagged_text,
        point_zm_tagged_text,
        point_text,
        multipoint_tagged_text,
        multipoint_text,
        parse_error,
        end_of_input
    };

    wkt_lexer(const char* source)
        : content(source)
    {
        start = cursor = source;
        limit          = content + strlen(source);
    }

    token_type scan()
    {

        /// pointer for backtracking information
        const char* marker = nullptr;

        start = cursor;

        
{
	char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,  64,  64,   0,   0,  64,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 64,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *cursor;
	if (yych <= '(') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto shapes_wkt_lexer_3;
			goto shapes_wkt_lexer_5;
		} else {
			if (yych <= '\n') goto shapes_wkt_lexer_2;
			if (yych <= '\'') goto shapes_wkt_lexer_5;
			goto shapes_wkt_lexer_7;
		}
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') goto shapes_wkt_lexer_5;
			goto shapes_wkt_lexer_8;
		} else {
			if (yych == 'P') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_5;
		}
	}
shapes_wkt_lexer_2:
	cursor = marker;
	goto shapes_wkt_lexer_6;
shapes_wkt_lexer_3:
	++cursor;
	{ return token_type::end_of_input; }
shapes_wkt_lexer_5:
	++cursor;
shapes_wkt_lexer_6:
	{ return token_type::parse_error; }
shapes_wkt_lexer_7:
	yych = *(marker = ++cursor);
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych <= 0x08) goto shapes_wkt_lexer_6;
			goto shapes_wkt_lexer_11;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_11;
			goto shapes_wkt_lexer_6;
		}
	} else {
		if (yych <= '-') {
			if (yych <= ' ') goto shapes_wkt_lexer_11;
			if (yych <= ',') goto shapes_wkt_lexer_6;
			goto shapes_wkt_lexer_11;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_6;
			if (yych <= '9') goto shapes_wkt_lexer_11;
			goto shapes_wkt_lexer_6;
		}
	}
shapes_wkt_lexer_8:
	yych = *(marker = ++cursor);
	if (yych == 'M') goto shapes_wkt_lexer_16;
	goto shapes_wkt_lexer_6;
shapes_wkt_lexer_9:
	yych = *(marker = ++cursor);
	if (yych == 'O') goto shapes_wkt_lexer_17;
	goto shapes_wkt_lexer_6;
shapes_wkt_lexer_10:
	yych = *++cursor;
shapes_wkt_lexer_11:
	if (yybm[0+yych] & 64) {
		goto shapes_wkt_lexer_10;
	}
	if (yych <= '/') {
		if (yych != '-') goto shapes_wkt_lexer_2;
	} else {
		if (yych <= '0') goto shapes_wkt_lexer_13;
		if (yych <= '9') goto shapes_wkt_lexer_14;
		goto shapes_wkt_lexer_2;
	}
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '0') goto shapes_wkt_lexer_13;
	if (yych <= '9') goto shapes_wkt_lexer_14;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_13:
	yych = *++cursor;
	if (yych <= '9') {
		if (yych <= '-') {
			if (yych <= ',') goto shapes_wkt_lexer_19;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '.') goto shapes_wkt_lexer_20;
			if (yych <= '/') goto shapes_wkt_lexer_19;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') goto shapes_wkt_lexer_19;
			goto shapes_wkt_lexer_21;
		} else {
			if (yych == 'e') goto shapes_wkt_lexer_21;
			goto shapes_wkt_lexer_19;
		}
	}
shapes_wkt_lexer_14:
	yych = *++cursor;
	if (yybm[0+yych] & 128) {
		goto shapes_wkt_lexer_14;
	}
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_18;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_18;
			if (yych <= 0x1F) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_18;
		}
	} else {
		if (yych <= 'D') {
			if (yych == '.') goto shapes_wkt_lexer_20;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_21;
			if (yych == 'e') goto shapes_wkt_lexer_21;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_16:
	yych = *++cursor;
	if (yych == 'P') goto shapes_wkt_lexer_22;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_17:
	yych = *++cursor;
	if (yych == 'I') goto shapes_wkt_lexer_23;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_18:
	yych = *++cursor;
shapes_wkt_lexer_19:
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_18;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_18;
			if (yych <= 0x1F) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_18;
		}
	} else {
		if (yych <= '/') {
			if (yych == '-') goto shapes_wkt_lexer_24;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '0') goto shapes_wkt_lexer_25;
			if (yych <= '9') goto shapes_wkt_lexer_26;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_20:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '9') goto shapes_wkt_lexer_28;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_21:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_30;
		goto shapes_wkt_lexer_2;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_30;
		if (yych <= '/') goto shapes_wkt_lexer_2;
		if (yych <= '9') goto shapes_wkt_lexer_31;
		goto shapes_wkt_lexer_2;
	}
shapes_wkt_lexer_22:
	yych = *++cursor;
	if (yych == 'T') goto shapes_wkt_lexer_33;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_23:
	yych = *++cursor;
	if (yych == 'N') goto shapes_wkt_lexer_34;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_24:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '0') goto shapes_wkt_lexer_25;
	if (yych <= '9') goto shapes_wkt_lexer_26;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_25:
	yych = *++cursor;
	if (yych <= '9') {
		if (yych <= '-') {
			if (yych <= ',') goto shapes_wkt_lexer_36;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '.') goto shapes_wkt_lexer_39;
			if (yych <= '/') goto shapes_wkt_lexer_36;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') goto shapes_wkt_lexer_36;
			goto shapes_wkt_lexer_40;
		} else {
			if (yych == 'e') goto shapes_wkt_lexer_40;
			goto shapes_wkt_lexer_36;
		}
	}
shapes_wkt_lexer_26:
	yych = *++cursor;
	if (yych <= ')') {
		if (yych <= '\r') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_35;
			if (yych <= '\f') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_35;
		} else {
			if (yych == ' ') goto shapes_wkt_lexer_35;
			if (yych <= '(') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_37;
		}
	} else {
		if (yych <= '9') {
			if (yych == '.') goto shapes_wkt_lexer_39;
			if (yych <= '/') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_26;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto shapes_wkt_lexer_2;
				goto shapes_wkt_lexer_40;
			} else {
				if (yych == 'e') goto shapes_wkt_lexer_40;
				goto shapes_wkt_lexer_2;
			}
		}
	}
shapes_wkt_lexer_28:
	yych = *++cursor;
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_18;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_18;
			if (yych <= 0x1F) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_18;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_28;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_21;
			if (yych == 'e') goto shapes_wkt_lexer_21;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_30:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych >= ':') goto shapes_wkt_lexer_2;
shapes_wkt_lexer_31:
	yych = *++cursor;
	if (yych <= '\r') {
		if (yych <= 0x08) goto shapes_wkt_lexer_2;
		if (yych <= '\n') goto shapes_wkt_lexer_18;
		if (yych <= '\f') goto shapes_wkt_lexer_2;
		goto shapes_wkt_lexer_18;
	} else {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_18;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_31;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_33:
	yych = *++cursor;
	if (yych == 'Y') goto shapes_wkt_lexer_37;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_34:
	yych = *++cursor;
	if (yych == 'T') goto shapes_wkt_lexer_41;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_35:
	yych = *++cursor;
shapes_wkt_lexer_36:
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_35;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_35;
			if (yych == ' ') goto shapes_wkt_lexer_35;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= '-') {
			if (yych <= ')') goto shapes_wkt_lexer_37;
			if (yych <= ',') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_44;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '0') goto shapes_wkt_lexer_45;
			if (yych <= '9') goto shapes_wkt_lexer_46;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_37:
	++cursor;
	{ return token_type::point_text; }
shapes_wkt_lexer_39:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '9') goto shapes_wkt_lexer_48;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_40:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_50;
		goto shapes_wkt_lexer_2;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_50;
		if (yych <= '/') goto shapes_wkt_lexer_2;
		if (yych <= '9') goto shapes_wkt_lexer_51;
		goto shapes_wkt_lexer_2;
	}
shapes_wkt_lexer_41:
	yych = *++cursor;
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych >= '\t') goto shapes_wkt_lexer_41;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_41;
		}
	} else {
		if (yych <= 'M') {
			if (yych <= ' ') goto shapes_wkt_lexer_41;
			if (yych >= 'M') goto shapes_wkt_lexer_53;
		} else {
			if (yych == 'Z') goto shapes_wkt_lexer_56;
		}
	}
	{ return token_type::point_tagged_text; }
shapes_wkt_lexer_44:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '0') goto shapes_wkt_lexer_45;
	if (yych <= '9') goto shapes_wkt_lexer_46;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_45:
	yych = *++cursor;
	if (yych <= '9') {
		if (yych <= '-') {
			if (yych <= ',') goto shapes_wkt_lexer_59;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '.') goto shapes_wkt_lexer_60;
			if (yych <= '/') goto shapes_wkt_lexer_59;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') goto shapes_wkt_lexer_59;
			goto shapes_wkt_lexer_61;
		} else {
			if (yych == 'e') goto shapes_wkt_lexer_61;
			goto shapes_wkt_lexer_59;
		}
	}
shapes_wkt_lexer_46:
	yych = *++cursor;
	if (yych <= ')') {
		if (yych <= '\r') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_58;
			if (yych <= '\f') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_58;
		} else {
			if (yych == ' ') goto shapes_wkt_lexer_58;
			if (yych <= '(') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_37;
		}
	} else {
		if (yych <= '9') {
			if (yych == '.') goto shapes_wkt_lexer_60;
			if (yych <= '/') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_46;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto shapes_wkt_lexer_2;
				goto shapes_wkt_lexer_61;
			} else {
				if (yych == 'e') goto shapes_wkt_lexer_61;
				goto shapes_wkt_lexer_2;
			}
		}
	}
shapes_wkt_lexer_48:
	yych = *++cursor;
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_35;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_35;
			if (yych == ' ') goto shapes_wkt_lexer_35;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= ')') goto shapes_wkt_lexer_37;
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_48;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_40;
			if (yych == 'e') goto shapes_wkt_lexer_40;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_50:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych >= ':') goto shapes_wkt_lexer_2;
shapes_wkt_lexer_51:
	yych = *++cursor;
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_35;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_35;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= ')') {
			if (yych <= ' ') goto shapes_wkt_lexer_35;
			if (yych <= '(') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_37;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_51;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_53:
	yych = *++cursor;
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_55;
		if (yych <= '\n') goto shapes_wkt_lexer_53;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_53;
		if (yych == ' ') goto shapes_wkt_lexer_53;
	}
shapes_wkt_lexer_55:
	{ return token_type::point_m_tagged_text; }
shapes_wkt_lexer_56:
	yych = *++cursor;
	if (yych == 'M') goto shapes_wkt_lexer_64;
	goto shapes_wkt_lexer_63;
shapes_wkt_lexer_57:
	{ return token_type::point_z_tagged_text; }
shapes_wkt_lexer_58:
	yych = *++cursor;
shapes_wkt_lexer_59:
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_58;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_58;
			if (yych == ' ') goto shapes_wkt_lexer_58;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= '-') {
			if (yych <= ')') goto shapes_wkt_lexer_37;
			if (yych <= ',') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_67;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '0') goto shapes_wkt_lexer_68;
			if (yych <= '9') goto shapes_wkt_lexer_69;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_60:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '9') goto shapes_wkt_lexer_71;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_61:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_73;
		goto shapes_wkt_lexer_2;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_73;
		if (yych <= '/') goto shapes_wkt_lexer_2;
		if (yych <= '9') goto shapes_wkt_lexer_74;
		goto shapes_wkt_lexer_2;
	}
shapes_wkt_lexer_62:
	yych = *++cursor;
shapes_wkt_lexer_63:
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_57;
		if (yych <= '\n') goto shapes_wkt_lexer_62;
		goto shapes_wkt_lexer_57;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_62;
		if (yych == ' ') goto shapes_wkt_lexer_62;
		goto shapes_wkt_lexer_57;
	}
shapes_wkt_lexer_64:
	yych = *++cursor;
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_66;
		if (yych <= '\n') goto shapes_wkt_lexer_64;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_64;
		if (yych == ' ') goto shapes_wkt_lexer_64;
	}
shapes_wkt_lexer_66:
	{ return token_type::point_zm_tagged_text; }
shapes_wkt_lexer_67:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '0') goto shapes_wkt_lexer_68;
	if (yych <= '9') goto shapes_wkt_lexer_69;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_68:
	yych = *++cursor;
	if (yych <= 'D') {
		if (yych == '.') goto shapes_wkt_lexer_78;
		goto shapes_wkt_lexer_77;
	} else {
		if (yych <= 'E') goto shapes_wkt_lexer_79;
		if (yych == 'e') goto shapes_wkt_lexer_79;
		goto shapes_wkt_lexer_77;
	}
shapes_wkt_lexer_69:
	yych = *++cursor;
	if (yych <= ')') {
		if (yych <= '\r') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_76;
			if (yych <= '\f') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_76;
		} else {
			if (yych == ' ') goto shapes_wkt_lexer_76;
			if (yych <= '(') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_37;
		}
	} else {
		if (yych <= '9') {
			if (yych == '.') goto shapes_wkt_lexer_78;
			if (yych <= '/') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_69;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto shapes_wkt_lexer_2;
				goto shapes_wkt_lexer_79;
			} else {
				if (yych == 'e') goto shapes_wkt_lexer_79;
				goto shapes_wkt_lexer_2;
			}
		}
	}
shapes_wkt_lexer_71:
	yych = *++cursor;
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_58;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_58;
			if (yych == ' ') goto shapes_wkt_lexer_58;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= ')') goto shapes_wkt_lexer_37;
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_71;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_61;
			if (yych == 'e') goto shapes_wkt_lexer_61;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_73:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych >= ':') goto shapes_wkt_lexer_2;
shapes_wkt_lexer_74:
	yych = *++cursor;
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_58;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_58;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= ')') {
			if (yych <= ' ') goto shapes_wkt_lexer_58;
			if (yych <= '(') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_37;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_74;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_76:
	yych = *++cursor;
shapes_wkt_lexer_77:
	if (yych <= '\r') {
		if (yych <= 0x08) goto shapes_wkt_lexer_2;
		if (yych <= '\n') goto shapes_wkt_lexer_76;
		if (yych <= '\f') goto shapes_wkt_lexer_2;
		goto shapes_wkt_lexer_76;
	} else {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_76;
		} else {
			if (yych == ')') goto shapes_wkt_lexer_37;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_78:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '9') goto shapes_wkt_lexer_80;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_79:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_82;
		goto shapes_wkt_lexer_2;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_82;
		if (yych <= '/') goto shapes_wkt_lexer_2;
		if (yych <= '9') goto shapes_wkt_lexer_83;
		goto shapes_wkt_lexer_2;
	}
shapes_wkt_lexer_80:
	yych = *++cursor;
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_76;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_76;
			if (yych == ' ') goto shapes_wkt_lexer_76;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= ')') goto shapes_wkt_lexer_37;
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_80;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_79;
			if (yych == 'e') goto shapes_wkt_lexer_79;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_82:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych >= ':') goto shapes_wkt_lexer_2;
shapes_wkt_lexer_83:
	yych = *++cursor;
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_76;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_76;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= ')') {
			if (yych <= ' ') goto shapes_wkt_lexer_76;
			if (yych <= '(') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_37;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_83;
			goto shapes_wkt_lexer_2;
		}
	}
}

    }

    std::string get_token() const
    {
        return std::string(reinterpret_cast<const char*>(start), static_cast<size_t>(cursor - start));
    }

  private:
    /// the buffer
    const char* content = nullptr;
    /// pointer to he beginning of the current symbol
    const char* start = nullptr;
    /// pointer to the current symbol
    const char* cursor = nullptr;
    /// pointer to the end of the buffer
    const char* limit = nullptr;
};

}  // namespace shapes
}  // namespace simo