/* Generated by re2c 1.1.1 on Fri Feb 15 20:17:29 2019 */
#pragma once

#include <iostream>

using namespace std;

class wkt_lexer {
public:

    enum token_type {
        point_tagged_text,
        point_z_tagged_text,
        point_m_tagged_text,
        point_zm_tagged_text,
        point_text,
        multipoint_tagged_text,
        multipoint_text,
        parse_error,
        end_of_input
    };

    wkt_lexer(const char *source)
            : content(source)
    {
        start = cursor = source;
        limit = content + strlen(source);
    }

    token_type scan() {

        /// pointer for backtracking information
        const char *marker = nullptr;

        start = cursor;

        
{
	char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,  64,  64,   0,   0,  64,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 64,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *cursor;
	if (yych <= '(') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto shapes_wkt_lexer_3;
			goto shapes_wkt_lexer_5;
		} else {
			if (yych <= '\n') goto shapes_wkt_lexer_2;
			if (yych <= '\'') goto shapes_wkt_lexer_5;
			goto shapes_wkt_lexer_7;
		}
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') goto shapes_wkt_lexer_5;
			goto shapes_wkt_lexer_8;
		} else {
			if (yych == 'P') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_5;
		}
	}
shapes_wkt_lexer_2:
	cursor = marker;
	goto shapes_wkt_lexer_6;
shapes_wkt_lexer_3:
	++cursor;
	{ return token_type::end_of_input; }
shapes_wkt_lexer_5:
	++cursor;
shapes_wkt_lexer_6:
	{ return token_type::parse_error; }
shapes_wkt_lexer_7:
	yych = *(marker = ++cursor);
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych <= 0x08) goto shapes_wkt_lexer_6;
			goto shapes_wkt_lexer_11;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_11;
			goto shapes_wkt_lexer_6;
		}
	} else {
		if (yych <= '-') {
			if (yych <= ' ') goto shapes_wkt_lexer_11;
			if (yych <= ',') goto shapes_wkt_lexer_6;
			goto shapes_wkt_lexer_11;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_6;
			if (yych <= '9') goto shapes_wkt_lexer_11;
			goto shapes_wkt_lexer_6;
		}
	}
shapes_wkt_lexer_8:
	yych = *(marker = ++cursor);
	if (yych == 'M') goto shapes_wkt_lexer_16;
	goto shapes_wkt_lexer_6;
shapes_wkt_lexer_9:
	yych = *(marker = ++cursor);
	if (yych == 'O') goto shapes_wkt_lexer_17;
	goto shapes_wkt_lexer_6;
shapes_wkt_lexer_10:
	yych = *++cursor;
shapes_wkt_lexer_11:
	if (yybm[0+yych] & 64) {
		goto shapes_wkt_lexer_10;
	}
	if (yych <= '/') {
		if (yych != '-') goto shapes_wkt_lexer_2;
	} else {
		if (yych <= '0') goto shapes_wkt_lexer_13;
		if (yych <= '9') goto shapes_wkt_lexer_14;
		goto shapes_wkt_lexer_2;
	}
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '0') goto shapes_wkt_lexer_13;
	if (yych <= '9') goto shapes_wkt_lexer_14;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_13:
	yych = *++cursor;
	if (yych <= '9') {
		if (yych <= '-') {
			if (yych <= ',') goto shapes_wkt_lexer_19;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '.') goto shapes_wkt_lexer_20;
			if (yych <= '/') goto shapes_wkt_lexer_19;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') goto shapes_wkt_lexer_19;
			goto shapes_wkt_lexer_21;
		} else {
			if (yych == 'e') goto shapes_wkt_lexer_21;
			goto shapes_wkt_lexer_19;
		}
	}
shapes_wkt_lexer_14:
	yych = *++cursor;
	if (yybm[0+yych] & 128) {
		goto shapes_wkt_lexer_14;
	}
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_18;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_18;
			if (yych <= 0x1F) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_18;
		}
	} else {
		if (yych <= 'D') {
			if (yych == '.') goto shapes_wkt_lexer_20;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_21;
			if (yych == 'e') goto shapes_wkt_lexer_21;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_16:
	yych = *++cursor;
	if (yych == 'P') goto shapes_wkt_lexer_22;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_17:
	yych = *++cursor;
	if (yych == 'I') goto shapes_wkt_lexer_23;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_18:
	yych = *++cursor;
shapes_wkt_lexer_19:
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_18;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_18;
			if (yych <= 0x1F) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_18;
		}
	} else {
		if (yych <= '/') {
			if (yych == '-') goto shapes_wkt_lexer_24;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '0') goto shapes_wkt_lexer_25;
			if (yych <= '9') goto shapes_wkt_lexer_26;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_20:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '9') goto shapes_wkt_lexer_28;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_21:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_30;
		goto shapes_wkt_lexer_2;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_30;
		if (yych <= '/') goto shapes_wkt_lexer_2;
		if (yych <= '9') goto shapes_wkt_lexer_31;
		goto shapes_wkt_lexer_2;
	}
shapes_wkt_lexer_22:
	yych = *++cursor;
	if (yych == 'T') goto shapes_wkt_lexer_33;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_23:
	yych = *++cursor;
	if (yych == 'N') goto shapes_wkt_lexer_34;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_24:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '0') goto shapes_wkt_lexer_25;
	if (yych <= '9') goto shapes_wkt_lexer_26;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_25:
	yych = *++cursor;
	if (yych <= '9') {
		if (yych <= '-') {
			if (yych <= ',') goto shapes_wkt_lexer_36;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '.') goto shapes_wkt_lexer_39;
			if (yych <= '/') goto shapes_wkt_lexer_36;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') goto shapes_wkt_lexer_36;
			goto shapes_wkt_lexer_40;
		} else {
			if (yych == 'e') goto shapes_wkt_lexer_40;
			goto shapes_wkt_lexer_36;
		}
	}
shapes_wkt_lexer_26:
	yych = *++cursor;
	if (yych <= ')') {
		if (yych <= '\r') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_35;
			if (yych <= '\f') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_35;
		} else {
			if (yych == ' ') goto shapes_wkt_lexer_35;
			if (yych <= '(') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_37;
		}
	} else {
		if (yych <= '9') {
			if (yych == '.') goto shapes_wkt_lexer_39;
			if (yych <= '/') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_26;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto shapes_wkt_lexer_2;
				goto shapes_wkt_lexer_40;
			} else {
				if (yych == 'e') goto shapes_wkt_lexer_40;
				goto shapes_wkt_lexer_2;
			}
		}
	}
shapes_wkt_lexer_28:
	yych = *++cursor;
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_18;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_18;
			if (yych <= 0x1F) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_18;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_28;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_21;
			if (yych == 'e') goto shapes_wkt_lexer_21;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_30:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych >= ':') goto shapes_wkt_lexer_2;
shapes_wkt_lexer_31:
	yych = *++cursor;
	if (yych <= '\r') {
		if (yych <= 0x08) goto shapes_wkt_lexer_2;
		if (yych <= '\n') goto shapes_wkt_lexer_18;
		if (yych <= '\f') goto shapes_wkt_lexer_2;
		goto shapes_wkt_lexer_18;
	} else {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_18;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_31;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_33:
	yych = *++cursor;
	if (yych == 'Y') goto shapes_wkt_lexer_37;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_34:
	yych = *++cursor;
	if (yych == 'T') goto shapes_wkt_lexer_41;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_35:
	yych = *++cursor;
shapes_wkt_lexer_36:
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_35;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_35;
			if (yych == ' ') goto shapes_wkt_lexer_35;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= '-') {
			if (yych <= ')') goto shapes_wkt_lexer_37;
			if (yych <= ',') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_43;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '0') goto shapes_wkt_lexer_44;
			if (yych <= '9') goto shapes_wkt_lexer_45;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_37:
	++cursor;
	{ return token_type::point_text; }
shapes_wkt_lexer_39:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '9') goto shapes_wkt_lexer_47;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_40:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_49;
		goto shapes_wkt_lexer_2;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_49;
		if (yych <= '/') goto shapes_wkt_lexer_2;
		if (yych <= '9') goto shapes_wkt_lexer_50;
		goto shapes_wkt_lexer_2;
	}
shapes_wkt_lexer_41:
	yych = *++cursor;
	if (yych == ' ') goto shapes_wkt_lexer_54;
	goto shapes_wkt_lexer_53;
shapes_wkt_lexer_42:
	{ return token_type::point_tagged_text; }
shapes_wkt_lexer_43:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '0') goto shapes_wkt_lexer_44;
	if (yych <= '9') goto shapes_wkt_lexer_45;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_44:
	yych = *++cursor;
	if (yych <= '9') {
		if (yych <= '-') {
			if (yych <= ',') goto shapes_wkt_lexer_56;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '.') goto shapes_wkt_lexer_57;
			if (yych <= '/') goto shapes_wkt_lexer_56;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') goto shapes_wkt_lexer_56;
			goto shapes_wkt_lexer_58;
		} else {
			if (yych == 'e') goto shapes_wkt_lexer_58;
			goto shapes_wkt_lexer_56;
		}
	}
shapes_wkt_lexer_45:
	yych = *++cursor;
	if (yych <= ')') {
		if (yych <= '\r') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_55;
			if (yych <= '\f') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_55;
		} else {
			if (yych == ' ') goto shapes_wkt_lexer_55;
			if (yych <= '(') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_37;
		}
	} else {
		if (yych <= '9') {
			if (yych == '.') goto shapes_wkt_lexer_57;
			if (yych <= '/') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_45;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto shapes_wkt_lexer_2;
				goto shapes_wkt_lexer_58;
			} else {
				if (yych == 'e') goto shapes_wkt_lexer_58;
				goto shapes_wkt_lexer_2;
			}
		}
	}
shapes_wkt_lexer_47:
	yych = *++cursor;
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_35;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_35;
			if (yych == ' ') goto shapes_wkt_lexer_35;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= ')') goto shapes_wkt_lexer_37;
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_47;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_40;
			if (yych == 'e') goto shapes_wkt_lexer_40;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_49:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych >= ':') goto shapes_wkt_lexer_2;
shapes_wkt_lexer_50:
	yych = *++cursor;
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_35;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_35;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= ')') {
			if (yych <= ' ') goto shapes_wkt_lexer_35;
			if (yych <= '(') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_37;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_50;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_52:
	yych = *++cursor;
shapes_wkt_lexer_53:
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_42;
		if (yych <= '\n') goto shapes_wkt_lexer_52;
		goto shapes_wkt_lexer_42;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_52;
		if (yych == ' ') goto shapes_wkt_lexer_52;
		goto shapes_wkt_lexer_42;
	}
shapes_wkt_lexer_54:
	yych = *++cursor;
	if (yych == 'M') goto shapes_wkt_lexer_59;
	if (yych == 'Z') goto shapes_wkt_lexer_62;
	goto shapes_wkt_lexer_53;
shapes_wkt_lexer_55:
	yych = *++cursor;
shapes_wkt_lexer_56:
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_55;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_55;
			if (yych == ' ') goto shapes_wkt_lexer_55;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= '-') {
			if (yych <= ')') goto shapes_wkt_lexer_37;
			if (yych <= ',') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_64;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '0') goto shapes_wkt_lexer_65;
			if (yych <= '9') goto shapes_wkt_lexer_66;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_57:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '9') goto shapes_wkt_lexer_68;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_58:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_70;
		goto shapes_wkt_lexer_2;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_70;
		if (yych <= '/') goto shapes_wkt_lexer_2;
		if (yych <= '9') goto shapes_wkt_lexer_71;
		goto shapes_wkt_lexer_2;
	}
shapes_wkt_lexer_59:
	yych = *++cursor;
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_61;
		if (yych <= '\n') goto shapes_wkt_lexer_59;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_59;
		if (yych == ' ') goto shapes_wkt_lexer_59;
	}
shapes_wkt_lexer_61:
	{ return token_type::point_m_tagged_text; }
shapes_wkt_lexer_62:
	yych = *++cursor;
	if (yych == 'M') goto shapes_wkt_lexer_75;
	goto shapes_wkt_lexer_74;
shapes_wkt_lexer_63:
	{ return token_type::point_z_tagged_text; }
shapes_wkt_lexer_64:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '0') goto shapes_wkt_lexer_65;
	if (yych <= '9') goto shapes_wkt_lexer_66;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_65:
	yych = *++cursor;
	if (yych <= 'D') {
		if (yych == '.') goto shapes_wkt_lexer_80;
		goto shapes_wkt_lexer_79;
	} else {
		if (yych <= 'E') goto shapes_wkt_lexer_81;
		if (yych == 'e') goto shapes_wkt_lexer_81;
		goto shapes_wkt_lexer_79;
	}
shapes_wkt_lexer_66:
	yych = *++cursor;
	if (yych <= ')') {
		if (yych <= '\r') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_78;
			if (yych <= '\f') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_78;
		} else {
			if (yych == ' ') goto shapes_wkt_lexer_78;
			if (yych <= '(') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_37;
		}
	} else {
		if (yych <= '9') {
			if (yych == '.') goto shapes_wkt_lexer_80;
			if (yych <= '/') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_66;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto shapes_wkt_lexer_2;
				goto shapes_wkt_lexer_81;
			} else {
				if (yych == 'e') goto shapes_wkt_lexer_81;
				goto shapes_wkt_lexer_2;
			}
		}
	}
shapes_wkt_lexer_68:
	yych = *++cursor;
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_55;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_55;
			if (yych == ' ') goto shapes_wkt_lexer_55;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= ')') goto shapes_wkt_lexer_37;
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_68;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_58;
			if (yych == 'e') goto shapes_wkt_lexer_58;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_70:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych >= ':') goto shapes_wkt_lexer_2;
shapes_wkt_lexer_71:
	yych = *++cursor;
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_55;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_55;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= ')') {
			if (yych <= ' ') goto shapes_wkt_lexer_55;
			if (yych <= '(') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_37;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_71;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_73:
	yych = *++cursor;
shapes_wkt_lexer_74:
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_63;
		if (yych <= '\n') goto shapes_wkt_lexer_73;
		goto shapes_wkt_lexer_63;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_73;
		if (yych == ' ') goto shapes_wkt_lexer_73;
		goto shapes_wkt_lexer_63;
	}
shapes_wkt_lexer_75:
	yych = *++cursor;
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_77;
		if (yych <= '\n') goto shapes_wkt_lexer_75;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_75;
		if (yych == ' ') goto shapes_wkt_lexer_75;
	}
shapes_wkt_lexer_77:
	{ return token_type::point_zm_tagged_text; }
shapes_wkt_lexer_78:
	yych = *++cursor;
shapes_wkt_lexer_79:
	if (yych <= '\r') {
		if (yych <= 0x08) goto shapes_wkt_lexer_2;
		if (yych <= '\n') goto shapes_wkt_lexer_78;
		if (yych <= '\f') goto shapes_wkt_lexer_2;
		goto shapes_wkt_lexer_78;
	} else {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_78;
		} else {
			if (yych == ')') goto shapes_wkt_lexer_37;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_80:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych <= '9') goto shapes_wkt_lexer_82;
	goto shapes_wkt_lexer_2;
shapes_wkt_lexer_81:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_84;
		goto shapes_wkt_lexer_2;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_84;
		if (yych <= '/') goto shapes_wkt_lexer_2;
		if (yych <= '9') goto shapes_wkt_lexer_85;
		goto shapes_wkt_lexer_2;
	}
shapes_wkt_lexer_82:
	yych = *++cursor;
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			if (yych <= '\n') goto shapes_wkt_lexer_78;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_78;
			if (yych == ' ') goto shapes_wkt_lexer_78;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= ')') goto shapes_wkt_lexer_37;
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_82;
			goto shapes_wkt_lexer_2;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_81;
			if (yych == 'e') goto shapes_wkt_lexer_81;
			goto shapes_wkt_lexer_2;
		}
	}
shapes_wkt_lexer_84:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_2;
	if (yych >= ':') goto shapes_wkt_lexer_2;
shapes_wkt_lexer_85:
	yych = *++cursor;
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych <= 0x08) goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_78;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_78;
			goto shapes_wkt_lexer_2;
		}
	} else {
		if (yych <= ')') {
			if (yych <= ' ') goto shapes_wkt_lexer_78;
			if (yych <= '(') goto shapes_wkt_lexer_2;
			goto shapes_wkt_lexer_37;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_2;
			if (yych <= '9') goto shapes_wkt_lexer_85;
			goto shapes_wkt_lexer_2;
		}
	}
}

    }

    string get_token() const {
        return string(reinterpret_cast<const char *>(start), static_cast<size_t>(cursor - start));
    }

private:
    /// the buffer
    const char* content = nullptr;
    /// pointer to he beginning of the current symbol
    const char* start = nullptr;
    /// pointer to the current symbol
    const char* cursor = nullptr;
    /// pointer to the end of the buffer
    const char* limit = nullptr;
};
