/* Generated by re2c 1.1.1 on Thu Apr 11 22:01:14 2019 */
#pragma once

#include <ciso646>
#include <iostream>

namespace simo
{

namespace shapes
{

/*!
 * @brief a Well-known text (WKT) markup language lexer
 *
 * @since 0.0.1
 */
class WktLexer
{
  public:

    /*!
     * @brief creates a wkt lexer from the given source
     * @param source the source string
     *
     * @since 0.0.1
     */
    WktLexer(const char* source)
        : content(source)
    {
        start = cursor = source;
        limit          = content + strlen(source);
    }

    /*!
     * @brief scan the next token
     * @return the numeric token identifier
     *
     * @since 0.0.1
     */
    int scan()
    {

        /// pointer for backtracking information
        const char* marker = nullptr;

        start = cursor;

        
{
	char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128, 128,   0,   0, 128,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *cursor;
	if (yych <= '0') {
		if (yych <= ' ') {
			if (yych <= '\n') {
				if (yych <= 0x00) goto shapes_wkt_lexer_2;
				if (yych <= 0x08) goto shapes_wkt_lexer_4;
				goto shapes_wkt_lexer_6;
			} else {
				if (yych == '\r') goto shapes_wkt_lexer_6;
				if (yych <= 0x1F) goto shapes_wkt_lexer_4;
				goto shapes_wkt_lexer_6;
			}
		} else {
			if (yych <= '+') {
				if (yych <= '\'') goto shapes_wkt_lexer_4;
				if (yych <= '(') goto shapes_wkt_lexer_8;
				if (yych <= ')') goto shapes_wkt_lexer_10;
				goto shapes_wkt_lexer_4;
			} else {
				if (yych <= ',') goto shapes_wkt_lexer_12;
				if (yych <= '-') goto shapes_wkt_lexer_14;
				if (yych <= '/') goto shapes_wkt_lexer_4;
				goto shapes_wkt_lexer_15;
			}
		}
	} else {
		if (yych <= 'P') {
			if (yych <= 'K') {
				if (yych <= '9') goto shapes_wkt_lexer_17;
				if (yych == 'E') goto shapes_wkt_lexer_19;
				goto shapes_wkt_lexer_4;
			} else {
				if (yych <= 'L') goto shapes_wkt_lexer_20;
				if (yych <= 'M') goto shapes_wkt_lexer_21;
				if (yych <= 'O') goto shapes_wkt_lexer_4;
				goto shapes_wkt_lexer_22;
			}
		} else {
			if (yych <= 'l') {
				if (yych == 'e') goto shapes_wkt_lexer_19;
				if (yych <= 'k') goto shapes_wkt_lexer_4;
				goto shapes_wkt_lexer_20;
			} else {
				if (yych <= 'm') goto shapes_wkt_lexer_21;
				if (yych == 'p') goto shapes_wkt_lexer_22;
				goto shapes_wkt_lexer_4;
			}
		}
	}
shapes_wkt_lexer_2:
	++cursor;
	{ return WKT_END_OF_INPUT; }
shapes_wkt_lexer_4:
	++cursor;
shapes_wkt_lexer_5:
	{ return WKT_PARSE_ERROR; }
shapes_wkt_lexer_6:
	++cursor;
	{ return scan(); }
shapes_wkt_lexer_8:
	++cursor;
	{ return WKT_LPAREN; }
shapes_wkt_lexer_10:
	++cursor;
	{ return WKT_RPAREN; }
shapes_wkt_lexer_12:
	++cursor;
	{ return WKT_COMMA; }
shapes_wkt_lexer_14:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_5;
	if (yych <= '0') goto shapes_wkt_lexer_15;
	if (yych <= '9') goto shapes_wkt_lexer_17;
	goto shapes_wkt_lexer_5;
shapes_wkt_lexer_15:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	if (yych <= 'D') {
		if (yych == '.') goto shapes_wkt_lexer_23;
	} else {
		if (yych <= 'E') goto shapes_wkt_lexer_25;
		if (yych == 'e') goto shapes_wkt_lexer_25;
	}
shapes_wkt_lexer_16:
	{ return WKT_NUM; }
shapes_wkt_lexer_17:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	if (yybm[0+yych] & 64) {
		goto shapes_wkt_lexer_17;
	}
	if (yych <= 'D') {
		if (yych == '.') goto shapes_wkt_lexer_23;
		goto shapes_wkt_lexer_16;
	} else {
		if (yych <= 'E') goto shapes_wkt_lexer_25;
		if (yych == 'e') goto shapes_wkt_lexer_25;
		goto shapes_wkt_lexer_16;
	}
shapes_wkt_lexer_19:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	if (yych == 'M') goto shapes_wkt_lexer_26;
	if (yych == 'm') goto shapes_wkt_lexer_26;
	goto shapes_wkt_lexer_5;
shapes_wkt_lexer_20:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	if (yych == 'I') goto shapes_wkt_lexer_27;
	if (yych == 'i') goto shapes_wkt_lexer_27;
	goto shapes_wkt_lexer_5;
shapes_wkt_lexer_21:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	if (yych == 'U') goto shapes_wkt_lexer_28;
	if (yych == 'u') goto shapes_wkt_lexer_28;
	goto shapes_wkt_lexer_5;
shapes_wkt_lexer_22:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	if (yych == 'O') goto shapes_wkt_lexer_29;
	if (yych == 'o') goto shapes_wkt_lexer_29;
	goto shapes_wkt_lexer_5;
shapes_wkt_lexer_23:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_24;
	if (yych <= '9') goto shapes_wkt_lexer_30;
shapes_wkt_lexer_24:
	cursor = marker;
	if (yyaccept <= 3) {
		if (yyaccept <= 1) {
			if (yyaccept == 0) {
				goto shapes_wkt_lexer_16;
			} else {
				goto shapes_wkt_lexer_5;
			}
		} else {
			if (yyaccept == 2) {
				goto shapes_wkt_lexer_50;
			} else {
				goto shapes_wkt_lexer_68;
			}
		}
	} else {
		if (yyaccept <= 5) {
			if (yyaccept == 4) {
				goto shapes_wkt_lexer_86;
			} else {
				goto shapes_wkt_lexer_89;
			}
		} else {
			if (yyaccept == 6) {
				goto shapes_wkt_lexer_111;
			} else {
				goto shapes_wkt_lexer_123;
			}
		}
	}
shapes_wkt_lexer_25:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_32;
		goto shapes_wkt_lexer_24;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_32;
		if (yych <= '/') goto shapes_wkt_lexer_24;
		if (yych <= '9') goto shapes_wkt_lexer_33;
		goto shapes_wkt_lexer_24;
	}
shapes_wkt_lexer_26:
	yych = *++cursor;
	if (yych == 'P') goto shapes_wkt_lexer_35;
	if (yych == 'p') goto shapes_wkt_lexer_35;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_27:
	yych = *++cursor;
	if (yych == 'N') goto shapes_wkt_lexer_36;
	if (yych == 'n') goto shapes_wkt_lexer_36;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_28:
	yych = *++cursor;
	if (yych == 'L') goto shapes_wkt_lexer_37;
	if (yych == 'l') goto shapes_wkt_lexer_37;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_29:
	yych = *++cursor;
	if (yych <= 'L') {
		if (yych == 'I') goto shapes_wkt_lexer_38;
		if (yych <= 'K') goto shapes_wkt_lexer_24;
		goto shapes_wkt_lexer_39;
	} else {
		if (yych <= 'i') {
			if (yych <= 'h') goto shapes_wkt_lexer_24;
			goto shapes_wkt_lexer_38;
		} else {
			if (yych == 'l') goto shapes_wkt_lexer_39;
			goto shapes_wkt_lexer_24;
		}
	}
shapes_wkt_lexer_30:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	if (yych <= 'D') {
		if (yych <= '/') goto shapes_wkt_lexer_16;
		if (yych <= '9') goto shapes_wkt_lexer_30;
		goto shapes_wkt_lexer_16;
	} else {
		if (yych <= 'E') goto shapes_wkt_lexer_25;
		if (yych == 'e') goto shapes_wkt_lexer_25;
		goto shapes_wkt_lexer_16;
	}
shapes_wkt_lexer_32:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_24;
	if (yych >= ':') goto shapes_wkt_lexer_24;
shapes_wkt_lexer_33:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_16;
	if (yych <= '9') goto shapes_wkt_lexer_33;
	goto shapes_wkt_lexer_16;
shapes_wkt_lexer_35:
	yych = *++cursor;
	if (yych == 'T') goto shapes_wkt_lexer_40;
	if (yych == 't') goto shapes_wkt_lexer_40;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_36:
	yych = *++cursor;
	if (yych == 'E') goto shapes_wkt_lexer_41;
	if (yych == 'e') goto shapes_wkt_lexer_41;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_37:
	yych = *++cursor;
	if (yych == 'T') goto shapes_wkt_lexer_42;
	if (yych == 't') goto shapes_wkt_lexer_42;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_38:
	yych = *++cursor;
	if (yych == 'N') goto shapes_wkt_lexer_43;
	if (yych == 'n') goto shapes_wkt_lexer_43;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_39:
	yych = *++cursor;
	if (yych == 'Y') goto shapes_wkt_lexer_44;
	if (yych == 'y') goto shapes_wkt_lexer_44;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_40:
	yych = *++cursor;
	if (yych == 'Y') goto shapes_wkt_lexer_45;
	if (yych == 'y') goto shapes_wkt_lexer_45;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_41:
	yych = *++cursor;
	if (yych == 'S') goto shapes_wkt_lexer_47;
	if (yych == 's') goto shapes_wkt_lexer_47;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_42:
	yych = *++cursor;
	if (yych == 'I') goto shapes_wkt_lexer_48;
	if (yych == 'i') goto shapes_wkt_lexer_48;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_43:
	yych = *++cursor;
	if (yych == 'T') goto shapes_wkt_lexer_49;
	if (yych == 't') goto shapes_wkt_lexer_49;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_44:
	yych = *++cursor;
	if (yych == 'G') goto shapes_wkt_lexer_51;
	if (yych == 'g') goto shapes_wkt_lexer_51;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_45:
	++cursor;
	{ return WKT_EMPTY_SET; }
shapes_wkt_lexer_47:
	yych = *++cursor;
	if (yych == 'T') goto shapes_wkt_lexer_52;
	if (yych == 't') goto shapes_wkt_lexer_52;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_48:
	yych = *++cursor;
	if (yych <= 'P') {
		if (yych == 'L') goto shapes_wkt_lexer_53;
		if (yych <= 'O') goto shapes_wkt_lexer_24;
		goto shapes_wkt_lexer_54;
	} else {
		if (yych <= 'l') {
			if (yych <= 'k') goto shapes_wkt_lexer_24;
			goto shapes_wkt_lexer_53;
		} else {
			if (yych == 'p') goto shapes_wkt_lexer_54;
			goto shapes_wkt_lexer_24;
		}
	}
shapes_wkt_lexer_49:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	if (yybm[0+yych] & 128) {
		goto shapes_wkt_lexer_55;
	}
	if (yych <= 'Z') {
		if (yych == 'M') goto shapes_wkt_lexer_57;
		if (yych >= 'Z') goto shapes_wkt_lexer_59;
	} else {
		if (yych <= 'm') {
			if (yych >= 'm') goto shapes_wkt_lexer_57;
		} else {
			if (yych == 'z') goto shapes_wkt_lexer_59;
		}
	}
shapes_wkt_lexer_50:
	{ return WKT_POINT_TAGGED_TEXT; }
shapes_wkt_lexer_51:
	yych = *++cursor;
	if (yych == 'O') goto shapes_wkt_lexer_61;
	if (yych == 'o') goto shapes_wkt_lexer_61;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_52:
	yych = *++cursor;
	if (yych == 'R') goto shapes_wkt_lexer_62;
	if (yych == 'r') goto shapes_wkt_lexer_62;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_53:
	yych = *++cursor;
	if (yych == 'I') goto shapes_wkt_lexer_63;
	if (yych == 'i') goto shapes_wkt_lexer_63;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_54:
	yych = *++cursor;
	if (yych == 'O') goto shapes_wkt_lexer_64;
	if (yych == 'o') goto shapes_wkt_lexer_64;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_55:
	yych = *++cursor;
	if (yybm[0+yych] & 128) {
		goto shapes_wkt_lexer_55;
	}
	if (yych <= 'Z') {
		if (yych == 'M') goto shapes_wkt_lexer_57;
		if (yych <= 'Y') goto shapes_wkt_lexer_24;
		goto shapes_wkt_lexer_59;
	} else {
		if (yych <= 'm') {
			if (yych <= 'l') goto shapes_wkt_lexer_24;
		} else {
			if (yych == 'z') goto shapes_wkt_lexer_59;
			goto shapes_wkt_lexer_24;
		}
	}
shapes_wkt_lexer_57:
	++cursor;
	{ return WKT_POINT_M_TAGGED_TEXT; }
shapes_wkt_lexer_59:
	yych = *++cursor;
	if (yych == 'M') goto shapes_wkt_lexer_65;
	if (yych == 'm') goto shapes_wkt_lexer_65;
	{ return WKT_POINT_Z_TAGGED_TEXT; }
shapes_wkt_lexer_61:
	yych = *++cursor;
	if (yych == 'N') goto shapes_wkt_lexer_67;
	if (yych == 'n') goto shapes_wkt_lexer_67;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_62:
	yych = *++cursor;
	if (yych == 'I') goto shapes_wkt_lexer_69;
	if (yych == 'i') goto shapes_wkt_lexer_69;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_63:
	yych = *++cursor;
	if (yych == 'N') goto shapes_wkt_lexer_70;
	if (yych == 'n') goto shapes_wkt_lexer_70;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_64:
	yych = *++cursor;
	if (yych <= 'L') {
		if (yych == 'I') goto shapes_wkt_lexer_71;
		if (yych <= 'K') goto shapes_wkt_lexer_24;
		goto shapes_wkt_lexer_72;
	} else {
		if (yych <= 'i') {
			if (yych <= 'h') goto shapes_wkt_lexer_24;
			goto shapes_wkt_lexer_71;
		} else {
			if (yych == 'l') goto shapes_wkt_lexer_72;
			goto shapes_wkt_lexer_24;
		}
	}
shapes_wkt_lexer_65:
	++cursor;
	{ return WKT_POINT_ZM_TAGGED_TEXT; }
shapes_wkt_lexer_67:
	yyaccept = 3;
	yych = *(marker = ++cursor);
	if (yych <= 'L') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_68;
			if (yych <= '\n') goto shapes_wkt_lexer_73;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_73;
			if (yych == ' ') goto shapes_wkt_lexer_73;
		}
	} else {
		if (yych <= 'l') {
			if (yych <= 'M') goto shapes_wkt_lexer_75;
			if (yych == 'Z') goto shapes_wkt_lexer_77;
		} else {
			if (yych <= 'm') goto shapes_wkt_lexer_75;
			if (yych == 'z') goto shapes_wkt_lexer_77;
		}
	}
shapes_wkt_lexer_68:
	{ return WKT_POLYGON_TAGGED_TEXT; }
shapes_wkt_lexer_69:
	yych = *++cursor;
	if (yych == 'N') goto shapes_wkt_lexer_79;
	if (yych == 'n') goto shapes_wkt_lexer_79;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_70:
	yych = *++cursor;
	if (yych == 'E') goto shapes_wkt_lexer_80;
	if (yych == 'e') goto shapes_wkt_lexer_80;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_71:
	yych = *++cursor;
	if (yych == 'N') goto shapes_wkt_lexer_81;
	if (yych == 'n') goto shapes_wkt_lexer_81;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_72:
	yych = *++cursor;
	if (yych == 'Y') goto shapes_wkt_lexer_82;
	if (yych == 'y') goto shapes_wkt_lexer_82;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_73:
	yych = *++cursor;
	if (yych <= 'L') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_24;
			if (yych <= '\n') goto shapes_wkt_lexer_73;
			goto shapes_wkt_lexer_24;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_73;
			if (yych == ' ') goto shapes_wkt_lexer_73;
			goto shapes_wkt_lexer_24;
		}
	} else {
		if (yych <= 'l') {
			if (yych <= 'M') goto shapes_wkt_lexer_75;
			if (yych == 'Z') goto shapes_wkt_lexer_77;
			goto shapes_wkt_lexer_24;
		} else {
			if (yych <= 'm') goto shapes_wkt_lexer_75;
			if (yych == 'z') goto shapes_wkt_lexer_77;
			goto shapes_wkt_lexer_24;
		}
	}
shapes_wkt_lexer_75:
	++cursor;
	{ return WKT_POLYGON_M_TAGGED_TEXT; }
shapes_wkt_lexer_77:
	yych = *++cursor;
	if (yych == 'M') goto shapes_wkt_lexer_83;
	if (yych == 'm') goto shapes_wkt_lexer_83;
	{ return WKT_POLYGON_Z_TAGGED_TEXT; }
shapes_wkt_lexer_79:
	yych = *++cursor;
	if (yych == 'G') goto shapes_wkt_lexer_85;
	if (yych == 'g') goto shapes_wkt_lexer_85;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_80:
	yych = *++cursor;
	if (yych == 'S') goto shapes_wkt_lexer_87;
	if (yych == 's') goto shapes_wkt_lexer_87;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_81:
	yych = *++cursor;
	if (yych == 'T') goto shapes_wkt_lexer_88;
	if (yych == 't') goto shapes_wkt_lexer_88;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_82:
	yych = *++cursor;
	if (yych == 'G') goto shapes_wkt_lexer_90;
	if (yych == 'g') goto shapes_wkt_lexer_90;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_83:
	++cursor;
	{ return WKT_POLYGON_ZM_TAGGED_TEXT; }
shapes_wkt_lexer_85:
	yyaccept = 4;
	yych = *(marker = ++cursor);
	if (yych <= 'L') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_86;
			if (yych <= '\n') goto shapes_wkt_lexer_91;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_91;
			if (yych == ' ') goto shapes_wkt_lexer_91;
		}
	} else {
		if (yych <= 'l') {
			if (yych <= 'M') goto shapes_wkt_lexer_93;
			if (yych == 'Z') goto shapes_wkt_lexer_95;
		} else {
			if (yych <= 'm') goto shapes_wkt_lexer_93;
			if (yych == 'z') goto shapes_wkt_lexer_95;
		}
	}
shapes_wkt_lexer_86:
	{ return WKT_LINESTRING_TAGGED_TEXT; }
shapes_wkt_lexer_87:
	yych = *++cursor;
	if (yych == 'T') goto shapes_wkt_lexer_97;
	if (yych == 't') goto shapes_wkt_lexer_97;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_88:
	yyaccept = 5;
	yych = *(marker = ++cursor);
	if (yych <= 'L') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_89;
			if (yych <= '\n') goto shapes_wkt_lexer_98;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_98;
			if (yych == ' ') goto shapes_wkt_lexer_98;
		}
	} else {
		if (yych <= 'l') {
			if (yych <= 'M') goto shapes_wkt_lexer_100;
			if (yych == 'Z') goto shapes_wkt_lexer_102;
		} else {
			if (yych <= 'm') goto shapes_wkt_lexer_100;
			if (yych == 'z') goto shapes_wkt_lexer_102;
		}
	}
shapes_wkt_lexer_89:
	{ return WKT_MULTIPOINT_TAGGED_TEXT; }
shapes_wkt_lexer_90:
	yych = *++cursor;
	if (yych == 'O') goto shapes_wkt_lexer_104;
	if (yych == 'o') goto shapes_wkt_lexer_104;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_91:
	yych = *++cursor;
	if (yych <= 'L') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_24;
			if (yych <= '\n') goto shapes_wkt_lexer_91;
			goto shapes_wkt_lexer_24;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_91;
			if (yych == ' ') goto shapes_wkt_lexer_91;
			goto shapes_wkt_lexer_24;
		}
	} else {
		if (yych <= 'l') {
			if (yych <= 'M') goto shapes_wkt_lexer_93;
			if (yych == 'Z') goto shapes_wkt_lexer_95;
			goto shapes_wkt_lexer_24;
		} else {
			if (yych <= 'm') goto shapes_wkt_lexer_93;
			if (yych == 'z') goto shapes_wkt_lexer_95;
			goto shapes_wkt_lexer_24;
		}
	}
shapes_wkt_lexer_93:
	++cursor;
	{ return WKT_LINESTRING_M_TAGGED_TEXT; }
shapes_wkt_lexer_95:
	yych = *++cursor;
	if (yych == 'M') goto shapes_wkt_lexer_105;
	if (yych == 'm') goto shapes_wkt_lexer_105;
	{ return WKT_LINESTRING_Z_TAGGED_TEXT; }
shapes_wkt_lexer_97:
	yych = *++cursor;
	if (yych == 'R') goto shapes_wkt_lexer_107;
	if (yych == 'r') goto shapes_wkt_lexer_107;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_98:
	yych = *++cursor;
	if (yych <= 'L') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_24;
			if (yych <= '\n') goto shapes_wkt_lexer_98;
			goto shapes_wkt_lexer_24;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_98;
			if (yych == ' ') goto shapes_wkt_lexer_98;
			goto shapes_wkt_lexer_24;
		}
	} else {
		if (yych <= 'l') {
			if (yych <= 'M') goto shapes_wkt_lexer_100;
			if (yych == 'Z') goto shapes_wkt_lexer_102;
			goto shapes_wkt_lexer_24;
		} else {
			if (yych <= 'm') goto shapes_wkt_lexer_100;
			if (yych == 'z') goto shapes_wkt_lexer_102;
			goto shapes_wkt_lexer_24;
		}
	}
shapes_wkt_lexer_100:
	++cursor;
	{ return WKT_MULTIPOINT_M_TAGGED_TEXT; }
shapes_wkt_lexer_102:
	yych = *++cursor;
	if (yych == 'M') goto shapes_wkt_lexer_108;
	if (yych == 'm') goto shapes_wkt_lexer_108;
	{ return WKT_MULTIPOINT_Z_TAGGED_TEXT; }
shapes_wkt_lexer_104:
	yych = *++cursor;
	if (yych == 'N') goto shapes_wkt_lexer_110;
	if (yych == 'n') goto shapes_wkt_lexer_110;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_105:
	++cursor;
	{ return WKT_LINESTRING_ZM_TAGGED_TEXT; }
shapes_wkt_lexer_107:
	yych = *++cursor;
	if (yych == 'I') goto shapes_wkt_lexer_112;
	if (yych == 'i') goto shapes_wkt_lexer_112;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_108:
	++cursor;
	{ return WKT_MULTIPOINT_ZM_TAGGED_TEXT; }
shapes_wkt_lexer_110:
	yyaccept = 6;
	yych = *(marker = ++cursor);
	if (yych <= 'L') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_111;
			if (yych <= '\n') goto shapes_wkt_lexer_113;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_113;
			if (yych == ' ') goto shapes_wkt_lexer_113;
		}
	} else {
		if (yych <= 'l') {
			if (yych <= 'M') goto shapes_wkt_lexer_115;
			if (yych == 'Z') goto shapes_wkt_lexer_117;
		} else {
			if (yych <= 'm') goto shapes_wkt_lexer_115;
			if (yych == 'z') goto shapes_wkt_lexer_117;
		}
	}
shapes_wkt_lexer_111:
	{ return WKT_MULTIPOLYGON_TAGGED_TEXT; }
shapes_wkt_lexer_112:
	yych = *++cursor;
	if (yych == 'N') goto shapes_wkt_lexer_119;
	if (yych == 'n') goto shapes_wkt_lexer_119;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_113:
	yych = *++cursor;
	if (yych <= 'L') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_24;
			if (yych <= '\n') goto shapes_wkt_lexer_113;
			goto shapes_wkt_lexer_24;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_113;
			if (yych == ' ') goto shapes_wkt_lexer_113;
			goto shapes_wkt_lexer_24;
		}
	} else {
		if (yych <= 'l') {
			if (yych <= 'M') goto shapes_wkt_lexer_115;
			if (yych == 'Z') goto shapes_wkt_lexer_117;
			goto shapes_wkt_lexer_24;
		} else {
			if (yych <= 'm') goto shapes_wkt_lexer_115;
			if (yych == 'z') goto shapes_wkt_lexer_117;
			goto shapes_wkt_lexer_24;
		}
	}
shapes_wkt_lexer_115:
	++cursor;
	{ return WKT_MULTIPOLYGON_M_TAGGED_TEXT; }
shapes_wkt_lexer_117:
	yych = *++cursor;
	if (yych == 'M') goto shapes_wkt_lexer_120;
	if (yych == 'm') goto shapes_wkt_lexer_120;
	{ return WKT_MULTIPOLYGON_Z_TAGGED_TEXT; }
shapes_wkt_lexer_119:
	yych = *++cursor;
	if (yych == 'G') goto shapes_wkt_lexer_122;
	if (yych == 'g') goto shapes_wkt_lexer_122;
	goto shapes_wkt_lexer_24;
shapes_wkt_lexer_120:
	++cursor;
	{ return WKT_MULTIPOLYGON_ZM_TAGGED_TEXT; }
shapes_wkt_lexer_122:
	yyaccept = 7;
	yych = *(marker = ++cursor);
	if (yych <= 'L') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_123;
			if (yych <= '\n') goto shapes_wkt_lexer_124;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_124;
			if (yych == ' ') goto shapes_wkt_lexer_124;
		}
	} else {
		if (yych <= 'l') {
			if (yych <= 'M') goto shapes_wkt_lexer_126;
			if (yych == 'Z') goto shapes_wkt_lexer_128;
		} else {
			if (yych <= 'm') goto shapes_wkt_lexer_126;
			if (yych == 'z') goto shapes_wkt_lexer_128;
		}
	}
shapes_wkt_lexer_123:
	{ return WKT_MULTILINESTRING_TAGGED_TEXT; }
shapes_wkt_lexer_124:
	yych = *++cursor;
	if (yych <= 'L') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_24;
			if (yych <= '\n') goto shapes_wkt_lexer_124;
			goto shapes_wkt_lexer_24;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_124;
			if (yych == ' ') goto shapes_wkt_lexer_124;
			goto shapes_wkt_lexer_24;
		}
	} else {
		if (yych <= 'l') {
			if (yych <= 'M') goto shapes_wkt_lexer_126;
			if (yych == 'Z') goto shapes_wkt_lexer_128;
			goto shapes_wkt_lexer_24;
		} else {
			if (yych <= 'm') goto shapes_wkt_lexer_126;
			if (yych == 'z') goto shapes_wkt_lexer_128;
			goto shapes_wkt_lexer_24;
		}
	}
shapes_wkt_lexer_126:
	++cursor;
	{ return WKT_MULTILINESTRING_M_TAGGED_TEXT; }
shapes_wkt_lexer_128:
	yych = *++cursor;
	if (yych == 'M') goto shapes_wkt_lexer_130;
	if (yych == 'm') goto shapes_wkt_lexer_130;
	{ return WKT_MULTILINESTRING_Z_TAGGED_TEXT; }
shapes_wkt_lexer_130:
	++cursor;
	{ return WKT_MULTILINESTRING_ZM_TAGGED_TEXT; }
}

    }

    /*!
     * @brief returns the current token string
     * @return the token string
     *
     * @since 0.0.1
     */
    std::string get_token() const
    {
        return std::string(reinterpret_cast<const char*>(start), static_cast<size_t>(cursor - start));
    }

  private:
    /// pointer to the buffer
    const char* content = nullptr;

    /// pointer to the beginning of the current token
    const char* start = nullptr;

    /// pointer to the current token
    const char* cursor = nullptr;

    /// pointer to the end of the buffer
    const char* limit = nullptr;
};

}  // namespace shapes
}  // namespace simo