/* Generated by re2c 1.1.1 on Sat Feb 16 15:12:58 2019 */
#pragma once

#include <iostream>

namespace simo
{
namespace shapes
{

class wkt_lexer
{
  public:
    enum token_type
    {
        point_tagged_text,
        point_z_tagged_text,
        point_m_tagged_text,
        point_zm_tagged_text,
        point_2_text,
        point_3_text,
        point_4_text,
        multipoint_tagged_text,
        multipoint_text,
        parse_error,
        end_of_input
    };

    wkt_lexer(const char* source)
        : content(source)
    {
        start = cursor = source;
        limit          = content + strlen(source);
    }

    token_type scan()
    {

        /// pointer for backtracking information
        const char* marker = nullptr;

        start = cursor;

        
{
	char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,  64,  64,   0,   0,  64,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 64,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *cursor;
	if (yych <= 0x1F) {
		if (yych <= '\t') {
			if (yych <= 0x00) goto shapes_wkt_lexer_2;
			if (yych <= 0x08) goto shapes_wkt_lexer_4;
			goto shapes_wkt_lexer_6;
		} else {
			if (yych <= '\n') goto shapes_wkt_lexer_7;
			if (yych == '\r') goto shapes_wkt_lexer_6;
			goto shapes_wkt_lexer_4;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= ' ') goto shapes_wkt_lexer_6;
			if (yych == '(') goto shapes_wkt_lexer_10;
			goto shapes_wkt_lexer_4;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_11;
			if (yych == 'P') goto shapes_wkt_lexer_12;
			goto shapes_wkt_lexer_4;
		}
	}
shapes_wkt_lexer_2:
	++cursor;
	{ return token_type::end_of_input; }
shapes_wkt_lexer_4:
	++cursor;
shapes_wkt_lexer_5:
	{ return token_type::parse_error; }
shapes_wkt_lexer_6:
	yych = *(marker = ++cursor);
	if (yybm[0+yych] & 64) {
		goto shapes_wkt_lexer_7;
	}
	if (yych == '(') goto shapes_wkt_lexer_13;
	if (yych == 'P') goto shapes_wkt_lexer_15;
	goto shapes_wkt_lexer_5;
shapes_wkt_lexer_7:
	yych = *++cursor;
	if (yybm[0+yych] & 64) {
		goto shapes_wkt_lexer_7;
	}
	if (yych == '(') goto shapes_wkt_lexer_13;
	if (yych == 'P') goto shapes_wkt_lexer_15;
shapes_wkt_lexer_9:
	cursor = marker;
	goto shapes_wkt_lexer_5;
shapes_wkt_lexer_10:
	yych = *(marker = ++cursor);
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych <= 0x08) goto shapes_wkt_lexer_5;
			goto shapes_wkt_lexer_14;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_14;
			goto shapes_wkt_lexer_5;
		}
	} else {
		if (yych <= '-') {
			if (yych <= ' ') goto shapes_wkt_lexer_14;
			if (yych <= ',') goto shapes_wkt_lexer_5;
			goto shapes_wkt_lexer_14;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_5;
			if (yych <= '9') goto shapes_wkt_lexer_14;
			goto shapes_wkt_lexer_5;
		}
	}
shapes_wkt_lexer_11:
	yych = *(marker = ++cursor);
	if (yych == 'M') goto shapes_wkt_lexer_20;
	goto shapes_wkt_lexer_5;
shapes_wkt_lexer_12:
	yych = *(marker = ++cursor);
	if (yych == 'O') goto shapes_wkt_lexer_21;
	goto shapes_wkt_lexer_5;
shapes_wkt_lexer_13:
	yych = *++cursor;
shapes_wkt_lexer_14:
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			if (yych <= '\n') goto shapes_wkt_lexer_13;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_13;
			if (yych <= 0x1F) goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_13;
		}
	} else {
		if (yych <= '/') {
			if (yych == '-') goto shapes_wkt_lexer_16;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '0') goto shapes_wkt_lexer_17;
			if (yych <= '9') goto shapes_wkt_lexer_18;
			goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_15:
	yych = *++cursor;
	if (yych == 'O') goto shapes_wkt_lexer_21;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_16:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_9;
	if (yych <= '0') goto shapes_wkt_lexer_17;
	if (yych <= '9') goto shapes_wkt_lexer_18;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_17:
	yych = *++cursor;
	if (yych <= '9') {
		if (yych <= '-') {
			if (yych <= ',') goto shapes_wkt_lexer_23;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '.') goto shapes_wkt_lexer_24;
			if (yych <= '/') goto shapes_wkt_lexer_23;
			goto shapes_wkt_lexer_9;
		}
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') goto shapes_wkt_lexer_23;
			goto shapes_wkt_lexer_25;
		} else {
			if (yych == 'e') goto shapes_wkt_lexer_25;
			goto shapes_wkt_lexer_23;
		}
	}
shapes_wkt_lexer_18:
	yych = *++cursor;
	if (yybm[0+yych] & 128) {
		goto shapes_wkt_lexer_18;
	}
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			if (yych <= '\n') goto shapes_wkt_lexer_22;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_22;
			if (yych <= 0x1F) goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_22;
		}
	} else {
		if (yych <= 'D') {
			if (yych == '.') goto shapes_wkt_lexer_24;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_25;
			if (yych == 'e') goto shapes_wkt_lexer_25;
			goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_20:
	yych = *++cursor;
	if (yych == 'P') goto shapes_wkt_lexer_26;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_21:
	yych = *++cursor;
	if (yych == 'I') goto shapes_wkt_lexer_27;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_22:
	yych = *++cursor;
shapes_wkt_lexer_23:
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			if (yych <= '\n') goto shapes_wkt_lexer_22;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_22;
			if (yych <= 0x1F) goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_22;
		}
	} else {
		if (yych <= '/') {
			if (yych == '-') goto shapes_wkt_lexer_28;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '0') goto shapes_wkt_lexer_29;
			if (yych <= '9') goto shapes_wkt_lexer_30;
			goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_24:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_9;
	if (yych <= '9') goto shapes_wkt_lexer_32;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_25:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_34;
		goto shapes_wkt_lexer_9;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_34;
		if (yych <= '/') goto shapes_wkt_lexer_9;
		if (yych <= '9') goto shapes_wkt_lexer_35;
		goto shapes_wkt_lexer_9;
	}
shapes_wkt_lexer_26:
	yych = *++cursor;
	if (yych == 'T') goto shapes_wkt_lexer_37;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_27:
	yych = *++cursor;
	if (yych == 'N') goto shapes_wkt_lexer_38;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_28:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_9;
	if (yych <= '0') goto shapes_wkt_lexer_29;
	if (yych <= '9') goto shapes_wkt_lexer_30;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_29:
	yych = *++cursor;
	if (yych <= '9') {
		if (yych <= '-') {
			if (yych <= ',') goto shapes_wkt_lexer_40;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '.') goto shapes_wkt_lexer_44;
			if (yych <= '/') goto shapes_wkt_lexer_40;
			goto shapes_wkt_lexer_9;
		}
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') goto shapes_wkt_lexer_40;
			goto shapes_wkt_lexer_45;
		} else {
			if (yych == 'e') goto shapes_wkt_lexer_45;
			goto shapes_wkt_lexer_40;
		}
	}
shapes_wkt_lexer_30:
	yych = *++cursor;
	if (yych <= ')') {
		if (yych <= '\r') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			if (yych <= '\n') goto shapes_wkt_lexer_39;
			if (yych <= '\f') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_39;
		} else {
			if (yych == ' ') goto shapes_wkt_lexer_39;
			if (yych <= '(') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_41;
		}
	} else {
		if (yych <= '9') {
			if (yych == '.') goto shapes_wkt_lexer_44;
			if (yych <= '/') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_30;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto shapes_wkt_lexer_9;
				goto shapes_wkt_lexer_45;
			} else {
				if (yych == 'e') goto shapes_wkt_lexer_45;
				goto shapes_wkt_lexer_9;
			}
		}
	}
shapes_wkt_lexer_32:
	yych = *++cursor;
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			if (yych <= '\n') goto shapes_wkt_lexer_22;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_22;
			if (yych <= 0x1F) goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_22;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= '/') goto shapes_wkt_lexer_9;
			if (yych <= '9') goto shapes_wkt_lexer_32;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_25;
			if (yych == 'e') goto shapes_wkt_lexer_25;
			goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_34:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_9;
	if (yych >= ':') goto shapes_wkt_lexer_9;
shapes_wkt_lexer_35:
	yych = *++cursor;
	if (yych <= '\r') {
		if (yych <= 0x08) goto shapes_wkt_lexer_9;
		if (yych <= '\n') goto shapes_wkt_lexer_22;
		if (yych <= '\f') goto shapes_wkt_lexer_9;
		goto shapes_wkt_lexer_22;
	} else {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_22;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_9;
			if (yych <= '9') goto shapes_wkt_lexer_35;
			goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_37:
	yych = *++cursor;
	if (yych == 'Y') goto shapes_wkt_lexer_46;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_38:
	yych = *++cursor;
	if (yych == 'T') goto shapes_wkt_lexer_47;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_39:
	yych = *++cursor;
shapes_wkt_lexer_40:
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			if (yych <= '\n') goto shapes_wkt_lexer_39;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_39;
			if (yych == ' ') goto shapes_wkt_lexer_39;
			goto shapes_wkt_lexer_9;
		}
	} else {
		if (yych <= '-') {
			if (yych <= ')') goto shapes_wkt_lexer_41;
			if (yych <= ',') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_50;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_9;
			if (yych <= '0') goto shapes_wkt_lexer_51;
			if (yych <= '9') goto shapes_wkt_lexer_52;
			goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_41:
	yych = *++cursor;
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_43;
		if (yych <= '\n') goto shapes_wkt_lexer_41;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_41;
		if (yych == ' ') goto shapes_wkt_lexer_41;
	}
shapes_wkt_lexer_43:
	{ return token_type::point_2_text; }
shapes_wkt_lexer_44:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_9;
	if (yych <= '9') goto shapes_wkt_lexer_54;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_45:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_56;
		goto shapes_wkt_lexer_9;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_56;
		if (yych <= '/') goto shapes_wkt_lexer_9;
		if (yych <= '9') goto shapes_wkt_lexer_57;
		goto shapes_wkt_lexer_9;
	}
shapes_wkt_lexer_46:
	++cursor;
	goto shapes_wkt_lexer_43;
shapes_wkt_lexer_47:
	yych = *++cursor;
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych >= '\t') goto shapes_wkt_lexer_47;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_47;
		}
	} else {
		if (yych <= 'M') {
			if (yych <= ' ') goto shapes_wkt_lexer_47;
			if (yych >= 'M') goto shapes_wkt_lexer_59;
		} else {
			if (yych == 'Z') goto shapes_wkt_lexer_62;
		}
	}
	{ return token_type::point_tagged_text; }
shapes_wkt_lexer_50:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_9;
	if (yych <= '0') goto shapes_wkt_lexer_51;
	if (yych <= '9') goto shapes_wkt_lexer_52;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_51:
	yych = *++cursor;
	if (yych <= '9') {
		if (yych <= '-') {
			if (yych <= ',') goto shapes_wkt_lexer_65;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '.') goto shapes_wkt_lexer_69;
			if (yych <= '/') goto shapes_wkt_lexer_65;
			goto shapes_wkt_lexer_9;
		}
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') goto shapes_wkt_lexer_65;
			goto shapes_wkt_lexer_70;
		} else {
			if (yych == 'e') goto shapes_wkt_lexer_70;
			goto shapes_wkt_lexer_65;
		}
	}
shapes_wkt_lexer_52:
	yych = *++cursor;
	if (yych <= ')') {
		if (yych <= '\r') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			if (yych <= '\n') goto shapes_wkt_lexer_64;
			if (yych <= '\f') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_64;
		} else {
			if (yych == ' ') goto shapes_wkt_lexer_64;
			if (yych <= '(') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_66;
		}
	} else {
		if (yych <= '9') {
			if (yych == '.') goto shapes_wkt_lexer_69;
			if (yych <= '/') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_52;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto shapes_wkt_lexer_9;
				goto shapes_wkt_lexer_70;
			} else {
				if (yych == 'e') goto shapes_wkt_lexer_70;
				goto shapes_wkt_lexer_9;
			}
		}
	}
shapes_wkt_lexer_54:
	yych = *++cursor;
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			if (yych <= '\n') goto shapes_wkt_lexer_39;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_39;
			if (yych == ' ') goto shapes_wkt_lexer_39;
			goto shapes_wkt_lexer_9;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= ')') goto shapes_wkt_lexer_41;
			if (yych <= '/') goto shapes_wkt_lexer_9;
			if (yych <= '9') goto shapes_wkt_lexer_54;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_45;
			if (yych == 'e') goto shapes_wkt_lexer_45;
			goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_56:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_9;
	if (yych >= ':') goto shapes_wkt_lexer_9;
shapes_wkt_lexer_57:
	yych = *++cursor;
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_39;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_39;
			goto shapes_wkt_lexer_9;
		}
	} else {
		if (yych <= ')') {
			if (yych <= ' ') goto shapes_wkt_lexer_39;
			if (yych <= '(') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_41;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_9;
			if (yych <= '9') goto shapes_wkt_lexer_57;
			goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_59:
	yych = *++cursor;
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_61;
		if (yych <= '\n') goto shapes_wkt_lexer_59;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_59;
		if (yych == ' ') goto shapes_wkt_lexer_59;
	}
shapes_wkt_lexer_61:
	{ return token_type::point_m_tagged_text; }
shapes_wkt_lexer_62:
	yych = *++cursor;
	if (yych == 'M') goto shapes_wkt_lexer_73;
	goto shapes_wkt_lexer_72;
shapes_wkt_lexer_63:
	{ return token_type::point_z_tagged_text; }
shapes_wkt_lexer_64:
	yych = *++cursor;
shapes_wkt_lexer_65:
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			if (yych <= '\n') goto shapes_wkt_lexer_64;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_64;
			if (yych == ' ') goto shapes_wkt_lexer_64;
			goto shapes_wkt_lexer_9;
		}
	} else {
		if (yych <= '-') {
			if (yych <= ')') goto shapes_wkt_lexer_66;
			if (yych <= ',') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_76;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_9;
			if (yych <= '0') goto shapes_wkt_lexer_77;
			if (yych <= '9') goto shapes_wkt_lexer_78;
			goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_66:
	yych = *++cursor;
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_68;
		if (yych <= '\n') goto shapes_wkt_lexer_66;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_66;
		if (yych == ' ') goto shapes_wkt_lexer_66;
	}
shapes_wkt_lexer_68:
	{ return token_type::point_3_text; }
shapes_wkt_lexer_69:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_9;
	if (yych <= '9') goto shapes_wkt_lexer_80;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_70:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_82;
		goto shapes_wkt_lexer_9;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_82;
		if (yych <= '/') goto shapes_wkt_lexer_9;
		if (yych <= '9') goto shapes_wkt_lexer_83;
		goto shapes_wkt_lexer_9;
	}
shapes_wkt_lexer_71:
	yych = *++cursor;
shapes_wkt_lexer_72:
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_63;
		if (yych <= '\n') goto shapes_wkt_lexer_71;
		goto shapes_wkt_lexer_63;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_71;
		if (yych == ' ') goto shapes_wkt_lexer_71;
		goto shapes_wkt_lexer_63;
	}
shapes_wkt_lexer_73:
	yych = *++cursor;
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_75;
		if (yych <= '\n') goto shapes_wkt_lexer_73;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_73;
		if (yych == ' ') goto shapes_wkt_lexer_73;
	}
shapes_wkt_lexer_75:
	{ return token_type::point_zm_tagged_text; }
shapes_wkt_lexer_76:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_9;
	if (yych <= '0') goto shapes_wkt_lexer_77;
	if (yych <= '9') goto shapes_wkt_lexer_78;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_77:
	yych = *++cursor;
	if (yych <= 'D') {
		if (yych == '.') goto shapes_wkt_lexer_90;
		goto shapes_wkt_lexer_86;
	} else {
		if (yych <= 'E') goto shapes_wkt_lexer_91;
		if (yych == 'e') goto shapes_wkt_lexer_91;
		goto shapes_wkt_lexer_86;
	}
shapes_wkt_lexer_78:
	yych = *++cursor;
	if (yych <= ')') {
		if (yych <= '\r') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			if (yych <= '\n') goto shapes_wkt_lexer_85;
			if (yych <= '\f') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_85;
		} else {
			if (yych == ' ') goto shapes_wkt_lexer_85;
			if (yych <= '(') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_87;
		}
	} else {
		if (yych <= '9') {
			if (yych == '.') goto shapes_wkt_lexer_90;
			if (yych <= '/') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_78;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto shapes_wkt_lexer_9;
				goto shapes_wkt_lexer_91;
			} else {
				if (yych == 'e') goto shapes_wkt_lexer_91;
				goto shapes_wkt_lexer_9;
			}
		}
	}
shapes_wkt_lexer_80:
	yych = *++cursor;
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			if (yych <= '\n') goto shapes_wkt_lexer_64;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_64;
			if (yych == ' ') goto shapes_wkt_lexer_64;
			goto shapes_wkt_lexer_9;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= ')') goto shapes_wkt_lexer_66;
			if (yych <= '/') goto shapes_wkt_lexer_9;
			if (yych <= '9') goto shapes_wkt_lexer_80;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_70;
			if (yych == 'e') goto shapes_wkt_lexer_70;
			goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_82:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_9;
	if (yych >= ':') goto shapes_wkt_lexer_9;
shapes_wkt_lexer_83:
	yych = *++cursor;
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_64;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_64;
			goto shapes_wkt_lexer_9;
		}
	} else {
		if (yych <= ')') {
			if (yych <= ' ') goto shapes_wkt_lexer_64;
			if (yych <= '(') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_66;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_9;
			if (yych <= '9') goto shapes_wkt_lexer_83;
			goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_85:
	yych = *++cursor;
shapes_wkt_lexer_86:
	if (yych <= '\r') {
		if (yych <= 0x08) goto shapes_wkt_lexer_9;
		if (yych <= '\n') goto shapes_wkt_lexer_85;
		if (yych <= '\f') goto shapes_wkt_lexer_9;
		goto shapes_wkt_lexer_85;
	} else {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_85;
		} else {
			if (yych != ')') goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_87:
	yych = *++cursor;
	if (yych <= '\f') {
		if (yych <= 0x08) goto shapes_wkt_lexer_89;
		if (yych <= '\n') goto shapes_wkt_lexer_87;
	} else {
		if (yych <= '\r') goto shapes_wkt_lexer_87;
		if (yych == ' ') goto shapes_wkt_lexer_87;
	}
shapes_wkt_lexer_89:
	{ return token_type::point_4_text; }
shapes_wkt_lexer_90:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_9;
	if (yych <= '9') goto shapes_wkt_lexer_92;
	goto shapes_wkt_lexer_9;
shapes_wkt_lexer_91:
	yych = *++cursor;
	if (yych <= ',') {
		if (yych == '+') goto shapes_wkt_lexer_94;
		goto shapes_wkt_lexer_9;
	} else {
		if (yych <= '-') goto shapes_wkt_lexer_94;
		if (yych <= '/') goto shapes_wkt_lexer_9;
		if (yych <= '9') goto shapes_wkt_lexer_95;
		goto shapes_wkt_lexer_9;
	}
shapes_wkt_lexer_92:
	yych = *++cursor;
	if (yych <= '(') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			if (yych <= '\n') goto shapes_wkt_lexer_85;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= '\r') goto shapes_wkt_lexer_85;
			if (yych == ' ') goto shapes_wkt_lexer_85;
			goto shapes_wkt_lexer_9;
		}
	} else {
		if (yych <= 'D') {
			if (yych <= ')') goto shapes_wkt_lexer_87;
			if (yych <= '/') goto shapes_wkt_lexer_9;
			if (yych <= '9') goto shapes_wkt_lexer_92;
			goto shapes_wkt_lexer_9;
		} else {
			if (yych <= 'E') goto shapes_wkt_lexer_91;
			if (yych == 'e') goto shapes_wkt_lexer_91;
			goto shapes_wkt_lexer_9;
		}
	}
shapes_wkt_lexer_94:
	yych = *++cursor;
	if (yych <= '/') goto shapes_wkt_lexer_9;
	if (yych >= ':') goto shapes_wkt_lexer_9;
shapes_wkt_lexer_95:
	yych = *++cursor;
	if (yych <= 0x1F) {
		if (yych <= '\n') {
			if (yych <= 0x08) goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_85;
		} else {
			if (yych == '\r') goto shapes_wkt_lexer_85;
			goto shapes_wkt_lexer_9;
		}
	} else {
		if (yych <= ')') {
			if (yych <= ' ') goto shapes_wkt_lexer_85;
			if (yych <= '(') goto shapes_wkt_lexer_9;
			goto shapes_wkt_lexer_87;
		} else {
			if (yych <= '/') goto shapes_wkt_lexer_9;
			if (yych <= '9') goto shapes_wkt_lexer_95;
			goto shapes_wkt_lexer_9;
		}
	}
}

    }

    std::string get_token() const
    {
        return std::string(reinterpret_cast<const char*>(start), static_cast<size_t>(cursor - start));
    }

  private:
    /// pointer to the buffer
    const char* content = nullptr;
    /// pointer to the beginning of the current token
    const char* start = nullptr;
    /// pointer to the current token
    const char* cursor = nullptr;
    /// pointer to the end of the buffer
    const char* limit = nullptr;
};

}  // namespace shapes
}  // namespace simo