dist: trusty
sudo: false
language: cpp

before_script:
  - pip install --user cpp-coveralls

script:
  - cmake .
  - cmake -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER="g++-6" --build . -- -j2
  - |
    coveralls --build-root . --gcov-options '\-lp' \
      -e build/external \
      -e build/include \
      -e build/CMakeFiles/3.8.0 \
      -e build/CMakeFiles/feature_tests.c \
      -e build/CMakeFiles/feature_tests.cxx