dist: trusty
sudo: false
language: cpp

compiler: gcc
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-4.9', 'ninja-build']

before_script:
  - pip install --user cpp-coveralls

script:
  - cmake .
  - cmake --build . -- -j2
  - coveralls --build-root tests --include include/shapes --gcov 'gcov-4.9' --gcov-options '\-lp'
  - make test

env:
  - CMAKE_CXX_COMPILER=g++-4.9
  - ENABLE_COVERAGE=ON
