language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'ninja-build']
      env:
        - SHAPES_CXX=g++-8
        - SHAPES_CC=gcc-8
        - CTEST_OUTPUT_ON_FAILURE=1
        - GIT_NAME=travis-ci
        - GIT_EMAIL=pavel.simo@gmail.com
        - GITHUB_REPO=pavelsimo/pavelsimo.github.io
        - GIT_SOURCE=docs/html

      script:
        - $CC --version
        - $CXX --version
        - cmake . -DSHAPES_ENABLE_COVERAGE:BOOL=TRUE
        - cmake --build . -- -j2
        - ctest -V -j2

      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then "$TRAVIS_BUILD_DIR/thirdparty/git-update-ghpages/git-update-ghpages" -e; fi

install:
- if [[ "${SHAPES_CXX}" != "" ]]; then export CXX=${SHAPES_CXX}; export CC=${SHAPES_CC}; fi