language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'ninja-build']
      env:
        - COMPILER=g++-8
        - CCOMPILER=gcc-8
        - CXXFLAGS=-std=c++17

      script:
        - cmake . -DSHAPES_ENABLE_COVERAGE:BOOL=TRUE
        - cmake --build . -- -j2
        - ctest -j2

      after_success:
        - bash <(curl -s https://codecov.io/bash)

