dist: trusty
sudo: false
language: cpp

matrix:
include:

- os: linux
  env:
    - TEST="Coveralls"
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-6
        - g++-6
  before_script:
    - mkdir build
    - cd build
    - pip install --user cpp-coveralls

  script:
    - cmake -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER="g++-6" ..
    - make
    - make test
    - cd ..
    - |
      coveralls --build-root build --gcov-options '\-lp' \
        -e build/external \
        -e build/include \
        -e build/CMakeFiles/3.8.0 \
        -e build/CMakeFiles/feature_tests.c \
        -e build/CMakeFiles/feature_tests.cxx