dist: trusty
sudo: false
language: cpp

compiler: gcc
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-4.9', 'ninja-build']

before_script:
  - pip install --user cpp-coveralls

script:
  - cmake .
  - cmake --build . -- -j2

after_success:
  - coveralls --build-root tests --include include/shapes --gcov 'gcov-4.9' --gcov-options '\-lp'

env:
  - COMPILER=g++-4.9
  - CCOMPILER=gcc-4.9
  - CMAKE_OPTIONS=-DENABLE_COVERAGEE=ON
