dist: trusty
sudo: false
language: cpp

compiler: gcc
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-4.9', 'ninja-build']

script:
  - cmake . -DSHAPES_ENABLE_COVERAGE:BOOL=TRUE
  - cmake --build . --j2
  - ctest -j2

after_success:
  - bash <(curl -s https://codecov.io/bash)

