dist: trusty
sudo: false
language: cpp

matrix:
include:

- os: linux
  compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.9', 'ninja-build']

  before_script:
    - pip install --user cpp-coveralls

  script:
    - cmake .
    - cmake --build . -- -j2

  after_success:
    - coveralls --build-root tests --include include/simo --gcov 'gcov-4.9' --gcov-options '\-lp'

  env:
  - COMPILER=g++-4.9
  - CMAKE_OPTIONS=-DSHAPES_COVERAGE=ON
  - SHAPES_SINGLE_HEADER=OFF