image:
  - Visual Studio 2017

init:
  - cmake --version
  - msbuild /version

build_script:
- cmd: >-
    cd build
    cmake .. -G "Visual Studio 15"
    cmake --build . --config Release


test_script:
  - ctest -C Release -V --output-on-failure --verbose