image:
  - Visual Studio 2017

init:
  - cmake --version
  - msbuild /version

before_build:
  - cmake . -G "Visual Studio 15"

build_script:
- cmd: >-
    cmake --build . --config Release

test_script:
  - ctest -C Release -V --output-on-failure --verbose